serve:
	php artisan serve --host 0.0.0.0 --port=$(port)

serve_thien:
	php artisan serve --host 0.0.0.0 --port=8121

# serve_hung:
# 	php artisan serve --host 0.0.0.0 --port=8888888

# serve_tung:
# 	php artisan serve --host 0.0.0.0 --port=9999999